### ISSUE TITLE
Reactome_2016

### ISSUE THREAD

**Issue by swagatam101** [BioNinja/gseapy#7] opened 2016-08-30 16:43 UTC
Running prerank leads to the following issue, only with Reactome_2016 and Reactome_2015: 

/usr/software/conda/2.3.0/lib/python2.7/site-packages/gseapy/parser.pyc in <dictcomp>((line,))
    125         print("Downloading and generating Enrichr library gene sets..............")
    126         genesets_dict = { line.decode().split("\t")[0]: [gene.split(",")[0] for gene in line.decode().split("\t")[2:-1]] 
--> 127                           for line in response.iter_lines()}    
    128 
    129     else:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 65: ordinal not in range(128)

**Comment by BioNinja** [comment] 2016-08-31 11:00
This bug is caused by python2.7.x
And fixed by now # @swagatam101

**Closed** 2016-09-05 15:19 UTC
Labels: bug
